version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: simple_chat
      POSTGRES_DB: simple_chat
    ports:
      - 5432:5432
    volumes:
      - postgres-simple_chat-data:/var/lib/postgresql/data
    networks:
      - simple-chat-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - simple-chat-network
  api:
    build:
      context: simple-chat.api
      dockerfile: Dockerfile
    command: yarn start:dev
    restart: on-failure
    ports:
      - 3333:3333
    env_file:
      - ./simple-chat.api/.env
    volumes:
      - ./usr/src/app:/api
    networks:
      - simple-chat-network

  front:
    build:
      context: simple-chat.site
      dockerfile: Dockerfile
    command: yarn dev
    restart: on-failure
    ports:
      - 3000:3000
    env_file:
      - ./simple-chat.site/.env
    volumes:
      - ./usr/src/app:/site
    networks:
      - simple-chat-network
volumes:
  postgres-simple_chat-data:
    driver: local
networks:
  simple-chat-network: